import { spawn, type SpawnOptions } from "node:child_process";

/**
 * Child process helpers.
 *
 * Windows matters: everything here is userland and works the same on win32,
 * darwin and linux. The only platform branch is `shell`, because Node refuses
 * to execute `pnpm.cmd` / `npx.cmd` without one (and a bare `pnpm` does not
 * exist on Windows). No shell-specific syntax is ever generated by Cairn — we
 * only ever hand over a command and its arguments.
 */

export interface RunResult {
  code: number | null;
  signal: NodeJS.Signals | null;
  stdout: string;
  stderr: string;
  /** Set when the process could not be spawned at all (ENOENT, EACCES...). */
  error?: NodeJS.ErrnoException;
  /** Human-readable rendering of what was run, for error messages. */
  command: string;
}

export interface RunOptions {
  cwd: string;
  env?: NodeJS.ProcessEnv;
  /** Stream child output to these sinks as well as capturing it. */
  onStdout?: (chunk: string) => void;
  onStderr?: (chunk: string) => void;
  timeoutMs?: number;
}

const isWindows = process.platform === "win32";

/** Quote an argument for cmd.exe when we are forced to go through a shell. */
function quoteForShell(arg: string): string {
  if (arg.length > 0 && !/[\s"^&|<>()%!]/.test(arg)) return arg;
  return `"${arg.replace(/"/g, '\\"')}"`;
}

/**
 * Split a command line into argv. Handles single and double quotes; that is
 * all Cairn needs to accept a `--runner "node ./stub.mjs"` override on any
 * platform without asking a shell to do the parsing.
 */
export function tokenize(commandLine: string): string[] {
  const tokens: string[] = [];
  let current = "";
  let quote: '"' | "'" | null = null;
  let started = false;

  for (let i = 0; i < commandLine.length; i += 1) {
    const char = commandLine[i] as string;
    if (quote) {
      // A backslash only escapes the closing quote; everything else is literal
      // so Windows paths ("C:\proofs\run.mjs") survive untouched.
      if (char === "\\" && commandLine[i + 1] === quote) {
        current += quote;
        i += 1;
      } else if (char === quote) {
        quote = null;
      } else {
        current += char;
      }
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      started = true;
      continue;
    }
    if (/\s/.test(char)) {
      if (started || current.length > 0) tokens.push(current);
      current = "";
      started = false;
      continue;
    }
    current += char;
  }
  if (started || current.length > 0) tokens.push(current);
  return tokens;
}

/** Spawn `command` with `args`, capturing stdout/stderr. Never throws. */
export function runArgv(command: string, args: string[], options: RunOptions): Promise<RunResult> {
  const rendered = [command, ...args].join(" ");

  return new Promise((resolve) => {
    const spawnOptions: SpawnOptions = {
      cwd: options.cwd,
      env: { ...process.env, ...options.env },
      stdio: ["ignore", "pipe", "pipe"],
      // See the note at the top of the file.
      shell: isWindows,
      windowsHide: true,
    };

    const child = spawn(
      isWindows ? quoteForShell(command) : command,
      isWindows ? args.map(quoteForShell) : args,
      spawnOptions,
    );

    let stdout = "";
    let stderr = "";
    let settled = false;
    let timer: NodeJS.Timeout | undefined;

    const finish = (result: RunResult) => {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer);
      resolve(result);
    };

    child.stdout?.setEncoding("utf8");
    child.stderr?.setEncoding("utf8");
    child.stdout?.on("data", (chunk: string) => {
      stdout += chunk;
      options.onStdout?.(chunk);
    });
    child.stderr?.on("data", (chunk: string) => {
      stderr += chunk;
      options.onStderr?.(chunk);
    });

    child.on("error", (error) => {
      finish({
        code: null,
        signal: null,
        stdout,
        stderr,
        error: error as NodeJS.ErrnoException,
        command: rendered,
      });
    });

    child.on("close", (code, signal) => {
      finish({ code, signal, stdout, stderr, command: rendered });
    });

    if (options.timeoutMs && options.timeoutMs > 0) {
      timer = setTimeout(() => {
        child.kill();
        finish({
          code: null,
          signal: null,
          stdout,
          stderr,
          error: Object.assign(new Error(`timed out after ${options.timeoutMs}ms`), {
            code: "ETIMEDOUT",
          }) as NodeJS.ErrnoException,
          command: rendered,
        });
      }, options.timeoutMs);
    }
  });
}

/** Run a command line given as one string (config `setup` / `start` hooks). */
export function runCommandLine(commandLine: string, options: RunOptions): Promise<RunResult> {
  const [command, ...args] = tokenize(commandLine);
  if (!command) {
    return Promise.resolve({
      code: 0,
      signal: null,
      stdout: "",
      stderr: "",
      command: commandLine,
    });
  }
  return runArgv(command, args, options);
}

/** True when a run failed because the executable itself was not found. */
export function isMissingExecutable(result: RunResult): boolean {
  if (result.error?.code === "ENOENT") return true;
  // Windows goes through cmd.exe, which reports a missing command as exit 1
  // (or 9009) plus a message on stderr instead of an ENOENT on the spawn.
  if (isWindows && (result.code === 1 || result.code === 9009)) {
    return /is not recognized as an internal or external command|introuvable/i.test(result.stderr);
  }
  return false;
}
